version: '3.9'
services:
  mysql:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD: mysqlsecret
      - MYSQL_DATABASE: wpdb
      - MYSQL_USER: wpuser
      - MYSQL_PASSWORD: wpusersecret
    restart: always
  wordpress:
    image: wordpress
    
